kind: Template
apiVersion: v1
metadata:
  labels:
    app: kubernetes-image-puller
  name: kubernetes-image-puller
objects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: create-daemonset
  rules:
  - apiGroups:
    - apps
    resources:
    - daemonsets
    verbs:
    - create
    - delete
    - watch
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: create-daemonset
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: create-daemonset
  subjects:
  - kind: ServiceAccount
    name: che
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: che
